- src/js/Lightbox.js
When the image is initially being fetched a nice loading screen is displayed. And once that image has been fully loaded, the loading screen is dismissed and the image is displayed.
```js
let loadingClasses = this._buildClasses('loading');
addClasses(this.el, loadingClasses);
this.imgEl.onload = () => {
removeClasses(this.el, loadingClasses);
}
this.imgEl.setAttribute('src', imageURL);
```
The problem is that if the user clicks on the image for a second time (after it is dismissed initially), it will add this loading class, but the event `load` will never be fired again.
This fix simply prevents the `loadingClasses` from being added to images that have already been loaded once.
Addresses issue #39
> Closes #39 - By allowing a second click on image

- package.json
To support easier consumption by bundlers (like Webpack), the source of this module shouldn't be the original `/src` but instead the generated output `/dist` which will help with this issue https://github.com/imgix/luminous/issues/43
> Change package.json main to dist/luminous.min.js

- .travis.yml
Node.js 4 is EOL since last month.
> chore: add Node.js 6, 8 and 10, remove Node.js 4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- package.json
PR and issues templates help guide users to create better issues and PRs, which help contributors maintain the repo.
[issues]: ../../issues
> chore: add issues and PR templates

- package.json
- src/js/LuminousGallery.js
This PR implements the destroy() method that is [currently not implemented on the LuminousGallery](https://github.com/imgix/luminous/blob/8e6be3c5ed610487fd6175f1db4adf1f19fda5c3/src/js/LuminousGallery.js#L49) by destroying all instances.
Doesn't update README or tests since there is no mention of methods in the README and no tests for the gallery.
> feat(gallery): implement destroy() on LuminousGallery

- config/karma/karma.config.js
- tests.webpack.js
- webpack.config.js
This PR updates the webpack and closure config to ensure that all src files are included. The closure plugin we use has a test flag that didn't work initially as I thought, so after investigating this I was able to fix it. As a side-effect of this update, the bundle size is even smaller at 8KB, an improvement of 43% over the original bundle size.
- [N/A] Add new passing unit tests to cover the code introduced by your PR
- [N/A] Update the readme
- [N/A] Update or add any necessary API documentation
Steps:
1.  Check that CI passes
> fix: update closure file test to include more src files

- src/js/Luminous.js
- src/js/LuminousGallery.js
This PR uses [the approach preferred by the Closure docs](https://developers.google.com/closure/compiler/docs/api-tutorial3#export) to export the public API of the Luminous and LuminousGallery classes. This has to happen because Closure rewrites the names of the class methods, which prevents third-parties from calling methods by their proper names.
- [N/A] Add new passing unit tests to cover the code introduced by your PR
- [N/A] Update the readme
- [N/A] Update or add any necessary API documentation
Steps:
1.  Clone this PR, `npm install`
2. 	Run `npm run build:watch`
2.	Play around with drift in `index.html`. `console.log(new Luminous(...))` should show that everything is exported on the prototype.
> fix: export public API

- src/js/Luminous.js
- src/js/injectBaseStylesheet.js
- test/testLuminous.js
The point of this is to account for luminous being used in shadow roots.
By using `getRootNode` (if supported), we can get to the `#shadow-root` rather than `document`. If we're not in one, we get `document`.
Create an element just like in the added test. Its as simple as your target element for luminous being a child of a shadow root.
> feat: add shadow dom support for base styles

- README.md
- src/js/Luminous.js
- src/js/util/dom.js
- test/testLuminous.js
My recent PR fixed styles being injected into shadow roots, but I had overlooked the fact that the lightbox is still appended to the document.
This means the styles don't get used as the lightbox is in the wrong root.
This fix introduces:
* `appendToNode` option which allows you to set the parent as a node
* if in a shadow root, `appendToNode` defaults to the shadow root
* if not in a shadow root, `appendToNode` defaults to `body`
* `appendToSelector` defaults to `null`
* `appendToSelector` takes precedence over `appendToNode`
* Use the `parentEl` root document for style injection rather than the trigger's root document
Create a new luminous instance on an element in a shadow root.
> fix: support shadow roots for lightboxes

- .travis.yml
Currently Travis runs two builds per PR. One of these is a branch build, one of these is a PR build. This slows down PR times.
This PR configures Travis to only run branch builds on the master branch.
> chore(travis): only run build check on master and release branches

- README.md
This PR resolves #216 by modifying documentation in the [Theming section](https://github.com/imgix/luminous#theming) of this project's README. Certain content was shifted around for better organization, in addition to adding a call out for `luminous-basic.css` usage.
> docs: add clarity for `luminous-basic.css` usage

- package-lock.json
Output from `npm audit fix`:
```
fixed 365 of 367 vulnerabilities in 1822 scanned packages
2 vulnerabilities required manual review and could not be updated
```
> chore(deps): sync with npm audit fix

- src/js/Luminous.js
- test/testLuminous.js
This PR corrects logic that prevented users from overriding the default value (`true`) of the `closeWithEscape` and `injectBaseStyles` configs when instantiating a new `Luminous` object.
Fixes #478 #105
> fix: allow "closeWithEscape" and "injectBaseStyles" to be overriden when initializing

- build/banner.js
- package-lock.json
- package.json
- postcss.config.js
- webpack.config.js
Prepends a banner with this project's license details to each minified file generated, to the effect of:
```js
/*!
* Luminous v2.3.3
* Copyright 2015-2021, Zebrafish Labs
* Licensed under BSD-2 (https://github.com/imgix/luminous/blob/main/LICENSE.md)
*/
```
Resolves #552
> build(webpack): prepend license banner in minified JS files

- package-lock.json
- package.json
Resolves a peer dependency issue preventing `npm install` from completing
> chore(dev-deps): upgrade eslint to @7.30.0

- src/js/Luminous.js
This commit has the library read the version number from the `package.json` reducing the number of places where this needs to be changed by hand upon cutting a release. Note, the `bower.json` will still need to be updated by hand.
This change specifically has semantic-release support in mind.
This commit also applies some eslint rules to the file.
> fix: bring package version back in sync

- src/js/Luminous.js
This commit undoes the change where the version was being read from the
package.json and hard codes the version number to the correct number.
Semantic release will take care of bumping this for is future so
there's no need to read it from the package.json.
Not doing this meant that semantic-release would not properly detect
changes to the version numbers. IE, it could not find the text it needed
to replace for the version numbers. This makes sense since, afaik, it
does not evaluate the code when it searches for matching text. So,
`this.version = VERSION` for example would mean it'd be trying to
bump a the version number of `VERSION`, not whatever that variable
actually evaluates to.
> chore: hard code version number in `src/Luminous.js`

- .travis.yml
- package.json
This commit changes the travis release script to release on all
branches. It also changes the replace plugin to a regex instead of a
string, which is more reliable and matches the release plugin's docs
more closely. It also fixes an issue where the replacement files
directory was missing the `js` subdirectory.
> build: enable semantic release on all branches

- .travis.yml
This commit fixes an issue where travis node lts was set to 18. This caused build errors on CI.
> build(travis): pin node v17

- package-lock.json
- package.json
One of the renovate PRs merged in an outdated version of jasmine by mistake. This PR updates the jasmine dev-dep to the correct version.
> chore(dev-deps): update jasmine to v4.0.0
